name: Testes Automatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de que webdriver-manager está no requirements.txt

      - name: Executar os testes
        run: |
          python -m pytest tests/test_login.py
